(require 'asdf)
(asdf:oos 'asdf:load-op :abcl)
(asdf:oos 'asdf:load-op :test-abcl)
(asdf:oos 'asdf:load-op :ansi-abcl-compiled :force t)
(asdf:oos 'asdf:test-op :ansi-test-compiled :force t)
(ext:exit)