(in-package :fset-user)
(defun foo (x)
  (labels ((bar (x)
             (cond ((null x) nil)
                   ((eq (car x) '&rest) (tail (cadr x)))
                   (t (cons (car x) (bar (cdr x))))))
           (tail (x)
             (list 'local-tail x)))
    (bar x)))
